### ISSUE TITLE
Rust 2018 Edition Support

### ISSUE THREAD

**Issue by xpe** [pingcap/grpc-rs#256]
**Is your feature request related to a problem? Please describe.**

I'd like to use generated code in a Rust 2018 edition project.

What would it take to have grpc-rs support both Rust 2015 and 2018 editions?

**Additional context**

> The release of Rust 1.31.0 on December 6th will be the first release of “Rust 2018.”

https://blog.rust-lang.org/2018/07/27/what-is-rust-2018.html

**Comment by siddontang** [comment]
PTAL @Hoverbear

**Comment by xpe** [comment]
Currently, here is the change to Cargo.toml that I'm using to make the current auto-generated code compile in my Rust 2018 project:

```toml
[dependencies]
futures = "*" # grpcio
grpcio = "0.4"
protobuf = "*" # grpcio
```
